services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    environment:
      - TEAM_NAME=choco_pie
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    command: ["lb", "--trace=true"]
