networks:
  servers:
services:
  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"
    environment:
      - CONF_DB_HOST=db:8083
      - CONF_TEAM_NAME=choco_pie
    depends_on:
      - db

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"
    environment:
      - CONF_DB_HOST=db:8083
      - CONF_TEAM_NAME=choco_pie
    depends_on:
      - db

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"
    environment:
      - CONF_DB_HOST=db:8083
      - CONF_TEAM_NAME=choco_pie
    depends_on:
      - db

  db:
    build: .
    command: "db"
    networks:
      - servers
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - DB_PATH=/app/db-data
    volumes:
      - db_data:/app/db-data

volumes:
  db_data:
