name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and run integration tests
        run: |
          echo "Running integration tests with Docker Compose..."
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --build --exit-code-from test
          docker compose down

      - name: Run all tests
        run: |
          echo "Running all tests in the project..."
          go test -v -race -timeout 5m ./...
